version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: realestate-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: realestate
    volumes:
      - mongodb_data:/data/db
      - ./backend/data/seed:/docker-entrypoint-initdb.d
    networks:
      - realestate-network

  mongo-express:
    image: mongo-express:latest
    container_name: realestate-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - realestate-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: realestate-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDb__ConnectionString=mongodb://admin:password123@mongodb:27017
      - MongoDb__DatabaseName=realestate
    depends_on:
      - mongodb
    networks:
      - realestate-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: realestate-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - realestate-network

volumes:
  mongodb_data:

networks:
  realestate-network:
    driver: bridge